---
dependency:
  name: galaxy

driver:
  name: lxd

lint: |
  set -e
  ansible-lint .

platforms:
  - name: ${MOLECULE_DISTRO:-focal}-${ANSIBLE_VER:-ansible}
    alias: ubuntu/${MOLECULE_DISTRO:-focal}/amd64

provisioner:
  name: ansible
  playbooks:
    create: ../common/playbooks/create.yml
    destroy: ../common/playbooks/destroy.yml
    converge: ../common/playbooks/playbook.yml
  optoins:
    diff: true
  inventory:
    links:
      group_vars: group_vars

verifier:
  name: testinfra
  directory: ../common/tests
  options:
    s: true  # pytest の -s を有効化. テスト時に print() の標準出力結果を見るため.
    v: true
